--- #YAML:1.0
name:               App-TTYcolor
version:            0.11
abstract:           Set the colors in the TTY / Linux Virtual Console
author:
    - Magnus Woldrich <trapd00r@trapd00r.se>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Term::ExtendedColor::TTY:  Term::ExtendedColor::Colorschemes
resources:
    bugtracker:  https://github.com/trapd00r/ttycolor/issues
    repository:  https://github.com/trapd00r/ttycolor
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
